### ISSUE TITLE
help wanted  请假大佬问题

### ISSUE THREAD

**Issue by yangchris4** [Oscar1011/EasyXarr#1]
感谢无私分享这个方案！谢谢，但是我在自己配置的过程中遇到了几个问题，想要 请教您一下：

config里的配置
1.others 项：WxHost  看到注释写的是 **微信服务后台的访问地址**    这个是什么意思？是另外部署的微信管理平台吗？还是说是emby jellyfin 之类的后台地址？
2.企业微信的 EncodingAESKey ，看了腾讯的文档，配置回调服务，需要有三个配置项，分别是：URL, Token, EncodingAESKey。URL为回调服务地址，这个地址是需要自己另外搭建的吗？
![peizhi](https://user-images.githubusercontent.com/13220804/165432421-9c0ba737-8845-4a83-aa6b-8d23444c50c9.png)

**Comment by Oscar1011** [comment]
不好意思刚看到问题

问题1.  是的，跟emby/jellyfin 后台地址差不多。  WxHost   对应的就是 可以访问到你的服务器或者 nas 的地址 。 一般是你部署的环境的域名 接上 docker 暴露出来的端口号（默认是8000，具体看你docker 映射出来的端口）。  
例如你的nas 做了ddns ,  域名是  nas.123.xyz。 那么填写的就是 http://nas.123.xyz:8000 。
问题2.  一般情况下填写的Url和 WxHost 是一样的。 

这两个都是依赖外网访问才可以的。否则无法通过微信操作到部署的服务

**Comment by yangchris4** [comment]
> 

感谢耐心回复，谢谢！ 
搜索了一下，好像腾讯的那个回调地址不支持ipv6，家里是移动的，只有ipv6，用它做的ddns域名 通不过验证。
用了一台vps 安装nps转发 也不行，直接提示 **服务器异常，请稍候再试，**。暂时放弃了，谢谢

**Comment by Oscar1011** [comment]
需要docker 配置里填好生成的 Token, EncodingAESKey  重启一下，再在腾讯里验证才能成功哦，如果还失败就没办法了
